### PR TITLE
Add PostgreSQL JSONB data type.

### PR DESCRIPTION
**Pull request by halybang**
PostgreSQL JSONB data type support.

### CODE REVIEW

**Comment by npiganeau** [comment]
Thanks for your proposal. 

However, I'm not sure about the use case of this. Actually, I see the interest in a general purpose ORM where you could use it to store arbitrary JSON data while still using the ORM.

But in the case of Hexya, I'm really keen on having its design "business driven". In this respect, each field type is not only a database column type but is above all a business object field type. That is a type which we can find in real life (e.g. a partner name is of type 'char', an invoice date is of type 'date', etc.). Even relation fields (such as Many2One) mimic real life relation (between a partner and a sale order, for instance). Moreover, each type is rendered in the client as a specific widget for user interaction.

In the case of JSONB, I don't see the "real life" aspect of the field type:

- What kind of business data would we store there ? Wouldn't relation fields (M2O, O2M, ...) be more appropriate here for most use cases ?
- What would the rendering widget look like ? For which use case ?

**Comment by halybang** [comment]
Users can use JSONB data type for IoT projects.
Use hexya to manage IoT device: Device ID, serial,  customer relate with  ... etc.
Each IoT device can send difference kind of data to Hexya, then Hexya save to database (humanity, gps position ...). With that case, IMHO, using JSONB.

**Comment by changwuf31** [comment]
Qor has something like https://github.com/qor/serializable_meta for this kind of use case. It was used for the queue job system, https://github.com/qor/worker. Data is stored in two fields, a kind field (string), eg: ```"voucher", "shirt"```, and data field (jsonb), eg:``` '{"nominal": 10}', '{"size":"M","color":"white"}'```.

Another idea would be the polymorphic models.

**Comment by sylnsr** [comment]
This is actually a feature that I have seen requested a few time from Odoo and long to have myself from Odoo. One major use case is ETL .. as follows (simple outline):
 - Import data from from various disparate sources and store as JSON
 - Use scheduled task or user driven UI to process data from JSON to target tables in ERP

**Comment by npiganeau** [comment]
Ok, I can consider this new field type for the ETL use case. But to keep it consistent with concept, we should also have a display widget for JSONB type in https://github.com/hexya-addons/web

If any of you want to make a PR over there for that, I will consider merging this one too.

**Comment by halybang** [comment]
Because of hexya changed struct andc code so much, I close this. See PR [https://github.com/hexya-erp/hexya/pull/69](https://github.com/hexya-erp/hexya/pull/69)

**Pull request closed without merging**
